version: '3.5'
services:
  dnsmasq:
    container_name: dnsmasq
    image: strm/dnsmasq
    restart: always
    volumes:
      - ./dnsmasq/wfc.conf:/etc/dnsmasq.d/wfc.conf
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
  pkmn-server:
    container_name: pkmn-server
    build:
      dockerfile: ./pkmn-server/Dockerfile
      args:
        - ADMIN_USERNAME=your_username
        - ADMIN_PASSWORD=your_password
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8000:8000/tcp"
      - "9000:9000/tcp"
      - "9001:9001/tcp"
      - "9009:9009/tcp"
      - "9002:9002/tcp"
      - "9003:9003/tcp"
      - "9998:9998/tcp"
      - "27500:27500/tcp"
      - "27900:27900/tcp"
      - "27901:27901/tcp"
      - "28910:28910/tcp"
      - "29900:29900/tcp"
      - "29901:29901/tcp"
      - "29920:29920/tcp"